### PR TITLE
Added redirect client

### PR DESCRIPTION
**Pull request by Fjellvang**
In the Client.ts i had to add a check to se if we have embedded items when we have pagination properties, since the new endpoint is paginated but we dont have embedded data.

### CODE REVIEW

**Comment by sitereactor** [comment]
For the RedirectClient I would assume we need to override this standard api version header, so we send api-version: 2.3 for the redirect requests. 
Ref.: https://github.com/umbraco/Umbraco.Headless.Client.NodeJs/blob/master/src/ApiRequest.ts#L19

**Comment by Fjellvang** [comment]
Do you think it's enough to just bump it to 2.3 ? I mean if this version works with the apis which are defined in version 2.0 it should be enough right?

It's funny, because i did test the code without noticing this header, and it worked fine so i'm a bit confused

**Comment by sitereactor** [comment]
The way I understand it from the discussion on Slack - if we send 2.3 as the default header, then the CMS instance will reject the request, because it only supports up until 2.2.
If we keep the api-version as is in this library I would expect the CDP to not serve the Redirects API as its api-version is 2.3. But what did you test it against? The Redirects API has been deployed to both DEV and PROD now, so maybe do a test against PROD with a project that has the latest bundle?

**Comment by sitereactor** [comment]
The cms doesn't know about version 2.3, so that is as expected. I just wasn't sure if the Redirects api would respond if the api-version sent was 2.2 (which is lower than what this api is released under).

**Pull request merged**
