### PR TITLE
Replace node-fetch with axios so it also works in browsers

### PR DESCRIPTION
**Pull request by rasmusjp**

### CODE REVIEW

**Comment by sitereactor** [comment]
You probably need to rebase this, now that the Forms API changes has been merged.

**Comment by rasmusjp** [comment]
Waiting with rebase until #6 has been merged

**Comment by sitereactor** [comment]
@rasmusjp #6 is merged now 🌮

**Comment by rasmusjp** [comment]
👍 I've rebased with master

**Pull request merged**
